
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //async
        // async function fn(){
        //     return new Promise((resolve, reject) => {
        //         reject("warn reason");
        //     })
        // }

        // //结果总是一个 promise对象
        // fn().then(val => {}, reason => {

        //     console.warn(reason);
        // })

    
        //await...总会返回一个Promise成功的 值, 失败用try catch处理
        const p = new Promise((resolve, reject) => {
            // resolve('success');
            reject('fail');
        })

        async function fc(){
            try{
                let result = await p;
                console.log(result);
            }catch(reason){
                console.log(reason);
            }
           
        }

        fc();

    </script>
</body>
</html>